language: node_js
node_js:
 - 11
cache: yarn

branches:
 only:
  - master
  - stable

before_install:
 - curl -o- -L https://yarnpkg.com/install.sh | bash
 - export PATH="$HOME/.yarn/bin:$PATH"

install:
 - yarn install

script:
 - yarn test

deploy:
 provider: heroku
 api_key:
  secure: "$HEROKU_API_KEY"
 on:
  branch: master
  condition: $MY_ENV = super_awesome